version: "3"

services:
    web:
        build: .
        restart: always
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000 
        volumes:
            - .:/app
        depends_on: 
            - postgres    

    postgres:
        image: postgres:latest
        restart: always

        env_file:
            - database.env
        ports:
            - "5432:5432"
 
        volumes:
            - ./pgdata:/var/lib/postgresql/data/
 