# Generated by Django 3.0.5 on 2020-05-29 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sent_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='link send time'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_verification',
            field=models.BooleanField(default=False, verbose_name='sms verfication'),
        ),
    ]
