# Generated by Django 3.0.5 on 2020-10-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(blank=True, max_length=255, verbose_name='Card Id')),
                ('customer_id', models.CharField(blank=True, max_length=255, verbose_name='Customer Id')),
                ('last4', models.CharField(blank=True, max_length=255, verbose_name='Last 4 digits')),
                ('brand', models.CharField(blank=True, max_length=255, verbose_name='Brand of card')),
                ('exp_month', models.CharField(blank=True, max_length=255, verbose_name='Exp. month')),
                ('exp_year', models.CharField(blank=True, max_length=255, verbose_name='Exp. year')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Card holder name')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(blank=True, max_length=255, verbose_name='Card Id')),
                ('customer_id', models.CharField(blank=True, max_length=255, verbose_name='Customer Id')),
                ('charge_id', models.CharField(blank=True, max_length=255, verbose_name='Charge Id')),
                ('charge_object', models.CharField(blank=True, max_length=255, null=True, verbose_name='Object')),
                ('amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Amount')),
                ('amount_refunded', models.CharField(blank=True, max_length=255, null=True, verbose_name='Amount refunded')),
                ('application', models.CharField(blank=True, max_length=255, null=True, verbose_name='Application')),
                ('application_fee', models.CharField(blank=True, max_length=255, null=True, verbose_name='Application fee')),
                ('application_fee_amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Application fee amount')),
                ('balance_transaction', models.CharField(blank=True, max_length=255, verbose_name='Balance transaction')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('calculated_statement_descriptor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calculated statement descriptor')),
                ('captured', models.BooleanField()),
                ('created', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Currency')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('disputed', models.BooleanField()),
                ('failure_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Failure code')),
                ('failure_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Failure message')),
                ('fraud_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fraud details')),
                ('invoice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice')),
                ('livemode', models.BooleanField()),
                ('metadata', models.CharField(blank=True, max_length=255, null=True, verbose_name='Metadata')),
                ('on_behalf_of', models.CharField(blank=True, max_length=255, null=True, verbose_name='On behalf of')),
                ('order', models.CharField(blank=True, max_length=255, null=True, verbose_name='Order')),
                ('outcome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outcome')),
                ('paid', models.BooleanField()),
                ('payment_intent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment intent')),
                ('payment_method', models.CharField(blank=True, max_length=255, verbose_name='Card Id')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand')),
                ('address_line1_check', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line1 check')),
                ('address_postal_code_check', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address postal code check')),
                ('cvc_check', models.CharField(blank=True, max_length=255, null=True, verbose_name='CVC check')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('exp_month', models.CharField(blank=True, max_length=255, null=True, verbose_name='Exp month')),
                ('exp_year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Exp year')),
                ('fingerprint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fingerprint')),
                ('funding', models.CharField(blank=True, max_length=255, null=True, verbose_name='Funding')),
                ('installments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Installments')),
                ('last4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last4 digit')),
                ('network', models.CharField(blank=True, max_length=255, null=True, verbose_name='Network')),
                ('three_d_secure', models.CharField(blank=True, max_length=255, null=True, verbose_name='3D secure')),
                ('wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wallet')),
                ('charge_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('receipt_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Receipt email')),
                ('receipt_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Receipt number')),
                ('receipt_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Receipt URL')),
                ('refunded', models.BooleanField()),
                ('refunds_object', models.CharField(blank=True, max_length=255, null=True, verbose_name='Refunds object')),
                ('refunds_data', models.CharField(blank=True, max_length=255, null=True, verbose_name='Refunds data')),
                ('refunds_has_more', models.BooleanField()),
                ('refunds_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Refunds URL')),
                ('review', models.CharField(blank=True, max_length=255, null=True, verbose_name='Review')),
                ('shipping', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping')),
                ('source_transfer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source transfer')),
                ('statement_descriptor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Statement descriptor')),
                ('statement_descriptor_suffix', models.CharField(blank=True, max_length=255, null=True, verbose_name='Statement descriptor suffix')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('transfer_data', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transfer data')),
                ('transfer_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transfer group')),
                ('source', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post_category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post_show',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Emp',
        ),
        migrations.RemoveField(
            model_name='user_invitation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Role',
        ),
        migrations.DeleteModel(
            name='User_Social_Access',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='sample.jpg', max_length=255, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.DeleteModel(
            name='Company_Profile',
        ),
        migrations.DeleteModel(
            name='Company_Role',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Post_Category',
        ),
        migrations.DeleteModel(
            name='Post_Show',
        ),
        migrations.DeleteModel(
            name='User_Invitation',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
        migrations.AddField(
            model_name='charge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
