# Generated by Django 3.0.5 on 2020-10-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201026_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='follwer',
            new_name='follower',
        ),
    ]
