# Generated by Django 3.0.5 on 2020-10-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201026_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='icimageon',
            new_name='image',
        ),
    ]
