# Generated by Django 3.0.5 on 2020-10-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201026_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_number',
            new_name='last4',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='stripe_cusotmer_id',
            new_name='stripe_card_id',
        ),
    ]
