# Generated by Django 3.0.5 on 2020-10-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201027_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_expiration_date',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
