# Generated by Django 3.0.5 on 2020-10-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_faq_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
