# Generated by Django 3.0.5 on 2020-10-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201029_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Event Price'),
        ),
    ]
