# Generated by Django 3.0.5 on 2020-10-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201029_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorder',
            name='charge_id',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AddField(
            model_name='eventorder',
            name='charge_id',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
