# Generated by Django 3.0.5 on 2020-10-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201030_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorder',
            name='order_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('pending', 'Pending')], default='pending', max_length=222, null=True),
        ),
        migrations.AddField(
            model_name='eventorder',
            name='order_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('pending', 'Pending')], default='pending', max_length=222, null=True),
        ),
    ]
