# Generated by Django 3.0.5 on 2020-11-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_subscriptionplan_stripe_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Event Price'),
        ),
    ]
