# Generated by Django 3.0.5 on 2020-11-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201102_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='credit_required',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Event Credit required'),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_participants',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Event number of participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='remianing_spots',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Event Remianing spots'),
        ),
    ]
