# Generated by Django 3.0.5 on 2020-11-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201102_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='session_lenght',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Session lenght'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_zone',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Event timezone'),
        ),
    ]
