# Generated by Django 3.0.5 on 2020-11-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201103_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
