# Generated by Django 3.0.5 on 2020-11-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('direct_purchase', 'Direct_purchase')], default='credit', max_length=222, null=True),
        ),
    ]
