# Generated by Django 3.0.5 on 2020-11-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_card_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpracticeaudienceqa',
            name='question',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Question'),
        ),
    ]
