# Generated by Django 3.0.5 on 2020-11-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_eventpracticeaudienceqa_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact us', 'verbose_name_plural': 'Contact us'},
        ),
    ]
