# Generated by Django 3.0.5 on 2020-11-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201104_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Email'),
        ),
    ]
