# Generated by Django 3.0.5 on 2020-11-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20201126_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='earned_money',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
