# Generated by Django 3.0.5 on 2020-12-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_transfer',
            field=models.BooleanField(default=False, verbose_name='Is featured'),
        ),
    ]
