# Generated by Django 3.0.5 on 2020-12-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20201222_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencertransferredmoney',
            name='kuzo_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='influencertransferredmoney',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_transfer',
            field=models.BooleanField(default=False, verbose_name='Is transfred'),
        ),
    ]
