# Generated by Django 3.0.5 on 2020-12-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20201222_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencertransferredmoney',
            old_name='amount',
            new_name='transfer_amount',
        ),
    ]
