# Generated by Django 3.0.5 on 2020-12-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20201222_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventclass',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_transfer',
            field=models.BooleanField(default=False, verbose_name='Is transfered'),
        ),
    ]
