# Generated by Django 3.0.5 on 2021-01-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210121_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='influenceroffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
