# Generated by Django 3.0.5 on 2021-01-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_influenceroffer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencertransferredmoney',
            name='transfer_amount',
            field=models.CharField(blank=True, default=0, max_length=222, null=True),
        ),
    ]
