# Generated by Django 3.0.5 on 2021-01-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210127_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencertransferredmoney',
            name='kuzo_amount',
            field=models.CharField(blank=True, default=0, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='influencertransferredmoney',
            name='total_amount',
            field=models.CharField(blank=True, default=0, max_length=222, null=True),
        ),
    ]
